import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import Link from 'next/link';
import ImgCard from '../comps/ImgCard'
import NavBar from '../comps/NavBar/index'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <NavBar></NavBar>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">My First App</a>
        </h1>

        <Link href="/boiler"> Go to Boiler </Link>
        <ImgCard
          bg="#FDE8CA"
        >
          <h1>Beans</h1>
          <p>poop</p>
        </ImgCard>
        <ImgCard
        img="https://placekitten.com/200/300"
        tcl="#41412F"
       >

        </ImgCard>

        

       

        
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
